### PR TITLE
feat: add support for new XML structure for 2020.3+

### LINKED ISSUE #29: Jetbrains 2020.3 I can't afford it ,
recentProjects.xml No list
```
  <option name="recentPaths">
      <list>

````

### PR DESCRIPTION
**Pull request by MrMitch**
Hi !

The XML structure for the `recentProjects.xml` file has changed in JetBrains products version 2020.3.

The `<option name="recentPaths">` no longer exist and projects can appear in 2 sections :

- in `<option name="additionalInfo">`, as `<entry key="$PATH$">` items, where recent projects appear, whether or not they are part of a group
- in `<option name="groups">`, as `<option value="$PATH$">` items, where only the projects of a group appear, whether they are recent or not

Because of that, from 2020.3, a recent group project can appear in both sections, and a recent project which is not in a group can only appear in the first section.

(You can also see that the attribute from which we can get the path doesn't have the same name, `key` or `value`)

This PR maintains support for the old XML structure and also adds support for the new structure, taking care of only showing items once, even if they appear twice in the XML file.

Tested with a `recentProjects.xml` file from PhpStorm 2020.**_2_** and another from PhpStorm 2020.**_3_**.

Fixes #29

### CODE REVIEW

**Comment by PaulVanSchayck** [comment]
This fix works for me!

**Comment by MrMitch** [comment]
@PaulVanSchayck glad to hear it, thanks for the feedback !

**Comment by PaulVanSchayck** [comment]
On second review. I think the ordering is still off. Recent projects are not on top. My recentProject.xml seems to be ordered by bottom entry has been used last. But maybe a more robust way would be to order by `projectOpenTimestamp`.

**Comment by MrMitch** [comment]
Correct, there is no ordering in place, the elements appear in the order in which they are in the file. I wanted to keep this as simple as possible to facilitate the merge by @brpaz

**Comment by brpaz** [comment]
Hello. Looks good to me.

Regarding ordering, this extension uses the order of the items in the respective project files. I am not deeply familiar with the structure of these files, so If there is some way to provide more relevant results first, feel free to create another PR.

I will merge this one.

**Pull request merged**
