### PR TITLE
New IntelliJ recentProject.xml structure

### PR DESCRIPTION
**Pull request by sergius02**
Hi!

I dont't know when exactly but it seems that the recentProject.xml has been changed (i use IntelliJ Ultimate 2020.03 EAP) and now the paths are in

component[@name="RecentProjectsManager"][1]/option[@name="additionalInfo"]/map/entry

instead of

component[@name="RecentProjectsManager"][1]/option[@name="recentPaths"]/list/option
(my Android Studio still use this)

### CODE REVIEW

**Comment by brpaz** [comment]
Hey. Thanks for your PR. Please look at the [linting issues](https://github.com/brpaz/ulauncher-jetbrains/pull/26/checks?check_run_id=1263750733) and I will merge this, 

Thank you.

**Comment by iosifch** [comment]
I can't wait for this pull request to be merged!:)

**Comment by Shadear** [comment]
Hello, may you merge ?  😍 

I think he has fixed the issues.

**Comment by brpaz** [comment]
I think this is the same as #31 which is already merged? Can you confirm, please?

**Comment by sergius02** [comment]
Hi, yes, is the same as #31

**Pull request closed without merging**
